// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0FZ_WFdGu5WIg-W15HYd-rhHiP4_ewwc',
    appId: '1:985943100868:web:a59978b8d04b1b1c16e891',
    messagingSenderId: '985943100868',
    projectId: 'danaku-app-393b5',
    authDomain: 'danaku-app-393b5.firebaseapp.com',
    storageBucket: 'danaku-app-393b5.firebasestorage.app',
    measurementId: 'G-G3VGCV02Y0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7dFAboTSqQddbCQraDqLQfogBP0GzXd8',
    appId: '1:985943100868:android:bde1a33ec19a377a16e891',
    messagingSenderId: '985943100868',
    projectId: 'danaku-app-393b5',
    storageBucket: 'danaku-app-393b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCilBOYv4x790KtEZdwBt1Hm3MVd7FgK54',
    appId: '1:985943100868:ios:afa907818fbf5f2516e891',
    messagingSenderId: '985943100868',
    projectId: 'danaku-app-393b5',
    storageBucket: 'danaku-app-393b5.firebasestorage.app',
    iosBundleId: 'com.example.flutterManajemenkeuangan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCilBOYv4x790KtEZdwBt1Hm3MVd7FgK54',
    appId: '1:985943100868:ios:afa907818fbf5f2516e891',
    messagingSenderId: '985943100868',
    projectId: 'danaku-app-393b5',
    storageBucket: 'danaku-app-393b5.firebasestorage.app',
    iosBundleId: 'com.example.flutterManajemenkeuangan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0FZ_WFdGu5WIg-W15HYd-rhHiP4_ewwc',
    appId: '1:985943100868:web:c775ac9bf2a9428616e891',
    messagingSenderId: '985943100868',
    projectId: 'danaku-app-393b5',
    authDomain: 'danaku-app-393b5.firebaseapp.com',
    storageBucket: 'danaku-app-393b5.firebasestorage.app',
    measurementId: 'G-N534Z1WECX',
  );
}
